export type Task = {
  id: string;
  title: string;
  completed: boolean;
  priority: "Low" | "Medium" | "High";
  dueDate?: string;
    projectId: string;
    description: string;
    userId:string
};
// src/types/types.ts
 

export const priorityMap: { [key in Task['priority']]: number } = { 
  Low: 1, 
  Medium: 2, 
  High: 3 
};

 export type Project = {
  id?: string; // Optional: Generated by the server
  name: string;
  description?: string; // Optional: Project description
  userId: string; // Link projects to a user
  createdAt?: string; // Optional: Generated by the server
};